# Generated by Django 2.2.1 on 2019-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=20)),
                ('Question', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
