# Generated by Django 2.2.1 on 2019-06-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20190618_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Country',
            new_name='country',
        ),
    ]
