# Generated by Django 2.2.1 on 2019-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20190618_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Question',
            new_name='question',
        ),
    ]
