# Generated by Django 2.2.1 on 2019-06-22 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20190619_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('four', 'Four Wheeler'), ('two', 'Two Wheeler'), ('three', 'Three Wheeler')], default='two', max_length=15)),
                ('contactno', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('intime', models.DateTimeField()),
                ('spacealloted', models.CharField(max_length=10)),
                ('flooralloted', models.CharField(max_length=10)),
                ('tagno', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('book', 'What is your favourite book?'), ('city', 'What city you were born in?'), ('food', 'What is your favourite Food?'), ('place', 'Which is your favourite place to vacation')], default='book', max_length=50),
        ),
    ]
