# Generated by Django 2.2.1 on 2019-06-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20190622_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('food', 'What is your favourite Food?'), ('city', 'What city you were born in?'), ('place', 'Which is your favourite place to vacation'), ('book', 'What is your favourite book?')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='intime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler'), ('three', 'Three Wheeler')], default='two', max_length=15),
        ),
    ]
