# Generated by Django 2.2.1 on 2019-06-25 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20190624_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('three', 'Three Wheeler'), ('four', 'Four Wheeler'), ('two', 'Two Wheeler')], default='two', max_length=15)),
                ('tagno', models.CharField(max_length=20)),
                ('dateout', models.DateField(default=datetime.date.today)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('fare', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('food', 'What is your favourite Food?'), ('book', 'What is your favourite book?'), ('city', 'What city you were born in?'), ('place', 'Which is your favourite place to vacation')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('three', 'Three Wheeler'), ('four', 'Four Wheeler'), ('two', 'Two Wheeler')], default='two', max_length=15),
        ),
    ]
