# Generated by Django 2.2.1 on 2019-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20190625_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='mname',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('others', 'Others'), ('female', 'Female'), ('male', 'Male')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('food', 'What is your favourite Food?'), ('book', 'What is your favourite book?'), ('city', 'What city you were born in?'), ('place', 'Which is your favourite place to vacation')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=15),
        ),
    ]
