# Generated by Django 2.2.1 on 2019-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_auto_20190627_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleexit',
            name='dateout',
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('others', 'Others'), ('male', 'Male')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('four', 'Four Wheeler'), ('three', 'Three Wheeler'), ('two', 'Two Wheeler')], default='two', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='vehicle_type',
            field=models.CharField(choices=[('four', 'Four Wheeler'), ('three', 'Three Wheeler'), ('two', 'Two Wheeler')], default='two', max_length=15),
        ),
    ]
