# Generated by Django 2.2.1 on 2019-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_auto_20190627_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('city', 'What city you were born in?'), ('place', 'Which is your favourite place to vacation'), ('book', 'What is your favourite book?'), ('food', 'What is your favourite Food?')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('three', 'Three Wheeler'), ('two', 'Two Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='vehicle_type',
            field=models.CharField(choices=[('three', 'Three Wheeler'), ('two', 'Two Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=15),
        ),
    ]
