# Generated by Django 2.2.1 on 2019-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_auto_20190627_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='contactno',
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('place', 'Which is your favourite place to vacation'), ('book', 'What is your favourite book?'), ('food', 'What is your favourite Food?'), ('city', 'What city you were born in?')], default='book', max_length=50),
        ),
    ]
