# Generated by Django 2.2.1 on 2019-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_auto_20190628_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ques',
            field=models.CharField(choices=[('city', 'What city you were born in?'), ('book', 'What is your favourite book?'), ('food', 'What is your favourite Food?'), ('place', 'Which is your favourite place to vacation')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler'), ('three', 'Three Wheeler')], default='two', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='vehicle_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four Wheeler'), ('three', 'Three Wheeler')], default='two', max_length=15),
        ),
    ]
